
services:
  - type: web
    name: telegram-live-stream-bot
    env: python
    plan: starter
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install --no-cache-dir -r requirements.txt"
    startCommand: "python run.py"
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: YOUR_USER_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: SOURCE_URL
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
